# Generated by Django 5.0.7 on 2024-08-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TickerText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='Текст записанный в бегущей строке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания видео')),
            ],
            options={
                'verbose_name': 'Тект в бегущей строке',
                'verbose_name_plural': 'Тексты записанные в бегущей строке',
            },
        ),
    ]
