# Generated by Django 5.0.7 on 2024-08-01 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0002_alter_tickertext_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickertext',
            options={'verbose_name': 'Текст в бегущей строке', 'verbose_name_plural': 'Тексты записанные в бегущие строки'},
        ),
        migrations.AlterField(
            model_name='tickertext',
            name='text',
            field=models.CharField(max_length=64, validators=[django.core.validators.MaxLengthValidator(64)], verbose_name='Текст в бегущей строке'),
        ),
    ]
