# Generated by Django 5.0.7 on 2024-08-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0003_alter_tickertext_options_alter_tickertext_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickertext',
            name='text',
            field=models.CharField(max_length=64, verbose_name='Текст в бегущей строке'),
        ),
    ]
