# Generated by Django 5.0.7 on 2024-08-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0004_alter_tickertext_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickertext',
            name='text',
            field=models.CharField(max_length=32, verbose_name='Текст в бегущей строке'),
        ),
    ]
